import re
from typing import Any


# Finds each:
# Document: something.pdf, Page: 123
#
# It also correctly handles multiple citations inside one pair
# of brackets, for example:
#
# [Document: A.pdf, Page: 10; Document: B.pdf, Page: 20]
#
CITATION_PATTERN = re.compile(
    r"Document:\s*([^;\]\n]+?)\s*,\s*Page:\s*(\d+)",
    re.IGNORECASE,
)


def normalize_document_name(
    document: str,
) -> str:
    """
    Normalize document names for reliable comparison.

    This avoids validation failures caused only by:
    - capitalization
    - repeated spaces
    - leading/trailing whitespace
    """

    return " ".join(
        document.strip().split()
    ).casefold()


def build_allowed_citations(
    retrieved_chunks: list[dict[str, Any]],
) -> set[tuple[str, int]]:
    """
    Build normalized valid citations from retrieved chunks.

    Each citation is represented as:

        (normalized_document_name, page_number)
    """

    allowed: set[tuple[str, int]] = set()

    for chunk in retrieved_chunks:
        metadata = chunk.get(
            "metadata",
            {},
        )

        document = metadata.get(
            "document"
        )

        page = metadata.get(
            "page"
        )

        if (
            document is None
            or page is None
        ):
            continue

        try:
            page_number = int(page)

        except (
            TypeError,
            ValueError,
        ):
            continue

        normalized_document = (
            normalize_document_name(
                str(document)
            )
        )

        allowed.add(
            (
                normalized_document,
                page_number,
            )
        )

    return allowed


def extract_citations(
    answer: str,
) -> list[tuple[str, int]]:
    """
    Extract every Document/Page citation from an answer.

    Supports both:

        [Document: A.pdf, Page: 10]

    and:

        [Document: A.pdf, Page: 10;
         Document: B.pdf, Page: 20]
    """

    citations: list[
        tuple[str, int]
    ] = []

    matches = CITATION_PATTERN.findall(
        answer
    )

    for document, page in matches:
        document = document.strip()

        try:
            page_number = int(page)

        except ValueError:
            continue

        citations.append(
            (
                document,
                page_number,
            )
        )

    return citations


def validate_citations(
    answer: str,
    retrieved_chunks: list[dict[str, Any]],
) -> dict[str, Any]:
    """
    Validate citations generated by the LLM.

    A citation is valid only when the exact document/page
    combination exists in the retrieved context.
    """

    allowed = build_allowed_citations(
        retrieved_chunks
    )

    found = extract_citations(
        answer
    )

    valid: list[
        tuple[str, int]
    ] = []

    invalid: list[
        tuple[str, int]
    ] = []

    for document, page in found:
        normalized = (
            normalize_document_name(
                document
            ),
            page,
        )

        if normalized in allowed:
            valid.append(
                (
                    document,
                    page,
                )
            )

        else:
            invalid.append(
                (
                    document,
                    page,
                )
            )

    return {
        "valid": valid,
        "invalid": invalid,
        "all_valid": len(invalid) == 0,
        "citation_count": len(found),
    }